version: '3.9'

services:
  givethio-frontend:
    image: ghcr.io/giveth/giveth-dapp-v2:main
    container_name: givethio-frontend
    restart: always
    volumes:
      - .env:/usr/src/app/.env.local
    ports:
      - "3000"
    env_file:
      - .env
