export const categoryList = [
	{ name: 'community', value: 'Community', source: 'adhoc' },
	{ name: 'food', value: 'Food', source: 'adhoc' },
	{ name: 'non-profit', value: 'Non-profit', source: 'adhoc' },
	{ name: 'housing', value: 'Housing', source: 'adhoc' },
	{ name: 'technology', value: 'Technology', source: 'adhoc' },
	{ name: 'research', value: 'Research', source: 'adhoc' },
	{ name: 'nutrition', value: 'Nutrition', source: 'adhoc' },
	{ name: 'art-culture', value: 'Art & Culture', source: 'adhoc' },
	{ name: 'agriculture', value: 'Agriculture', source: 'IRIS' },
	{ name: 'air', value: 'Air', source: 'IRIS' },
	{ name: 'biodiversity', value: 'Biodiversity', source: 'IRIS' },
	{ name: 'climate', value: 'Climate', source: 'IRIS' },
	{ name: 'inclusion', value: 'Inclusion', source: 'IRIS' },
	{ name: 'education', value: 'Education', source: 'IRIS' },
	{ name: 'employment', value: 'Employment', source: 'IRIS' },
	{ name: 'energy', value: 'Energy', source: 'IRIS' },
	{ name: 'finance', value: 'Finance', source: 'IRIS' },
	{ name: 'health', value: 'Health', source: 'IRIS' },
	{ name: 'infrastructure', value: 'Infrastructure', source: 'IRIS' },
	{ name: 'land', value: 'Land', source: 'IRIS' },
	{ name: 'oceans', value: 'Oceans', source: 'IRIS' },
	{ name: 'pollution', value: 'Pollution', source: 'IRIS' },
	{ name: 'real-estate', value: 'Real Estate', source: 'IRIS' },
	{ name: 'waste', value: 'Waste', source: 'IRIS' },
	{ name: 'water', value: 'Water', source: 'IRIS' },
	{ name: 'other', value: 'Other', source: 'adhoc' },
];

export const maxSelectedCategory = 5;
